// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// coordi_cho
List coordi_cho(NumericVector atilde, NumericMatrix B, NumericVector betainit, double lambda, int iter_max);
RcppExport SEXP _pda_coordi_cho(SEXP atildeSEXP, SEXP BSEXP, SEXP betainitSEXP, SEXP lambdaSEXP, SEXP iter_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type atilde(atildeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betainit(betainitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(coordi_cho(atilde, B, betainit, lambda, iter_max));
    return rcpp_result_gen;
END_RCPP
}
// coordi_c
List coordi_c(NumericVector atilde, NumericMatrix B, NumericVector betainit, double lambda, int iter_max);
RcppExport SEXP _pda_coordi_c(SEXP atildeSEXP, SEXP BSEXP, SEXP betainitSEXP, SEXP lambdaSEXP, SEXP iter_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type atilde(atildeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betainit(betainitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type iter_max(iter_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(coordi_c(atilde, B, betainit, lambda, iter_max));
    return rcpp_result_gen;
END_RCPP
}
// cum_sum
arma::vec cum_sum(arma::vec& x, bool reversely);
RcppExport SEXP _pda_cum_sum(SEXP xSEXP, SEXP reverselySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type reversely(reverselySEXP);
    rcpp_result_gen = Rcpp::wrap(cum_sum(x, reversely));
    return rcpp_result_gen;
END_RCPP
}
// cum_sum_cols
arma::mat cum_sum_cols(arma::mat& x, bool reversely);
RcppExport SEXP _pda_cum_sum_cols(SEXP xSEXP, SEXP reverselySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type reversely(reverselySEXP);
    rcpp_result_gen = Rcpp::wrap(cum_sum_cols(x, reversely));
    return rcpp_result_gen;
END_RCPP
}
// Xotimes2
arma::mat Xotimes2(arma::mat& X);
RcppExport SEXP _pda_Xotimes2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(Xotimes2(X));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coxph_logL
double rcpp_coxph_logL(const arma::vec& beta, const arma::vec& time, const arma::vec& event, const arma::mat& z);
RcppExport SEXP _pda_rcpp_coxph_logL(SEXP betaSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coxph_logL(beta, time, event, z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coxph_logL_gradient
arma::vec rcpp_coxph_logL_gradient(const arma::vec& beta, const arma::vec& time, const arma::vec& event, const arma::mat& z);
RcppExport SEXP _pda_rcpp_coxph_logL_gradient(SEXP betaSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coxph_logL_gradient(beta, time, event, z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coxph_logL_hessian
arma::vec rcpp_coxph_logL_hessian(const arma::vec& beta, const arma::vec& time, const arma::vec& event, const arma::mat& z);
RcppExport SEXP _pda_rcpp_coxph_logL_hessian(SEXP betaSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coxph_logL_hessian(beta, time, event, z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coxph_logL_efron
double rcpp_coxph_logL_efron(const arma::vec& beta, const arma::vec& time, const arma::vec& event, const arma::mat& z);
RcppExport SEXP _pda_rcpp_coxph_logL_efron(SEXP betaSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coxph_logL_efron(beta, time, event, z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coxph_logL_gradient_efron
arma::vec rcpp_coxph_logL_gradient_efron(const arma::vec& beta, const arma::vec& time, const arma::vec& event, const arma::mat& z);
RcppExport SEXP _pda_rcpp_coxph_logL_gradient_efron(SEXP betaSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coxph_logL_gradient_efron(beta, time, event, z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coxph_logL_gradient_efron_dist
arma::vec rcpp_coxph_logL_gradient_efron_dist(const arma::vec& beta, const arma::vec& ind_machine_, bool& useLocal, const int dj_cutoff, const arma::vec& time, const arma::vec& event, const arma::mat& z);
RcppExport SEXP _pda_rcpp_coxph_logL_gradient_efron_dist(SEXP betaSEXP, SEXP ind_machine_SEXP, SEXP useLocalSEXP, SEXP dj_cutoffSEXP, SEXP timeSEXP, SEXP eventSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ind_machine_(ind_machine_SEXP);
    Rcpp::traits::input_parameter< bool& >::type useLocal(useLocalSEXP);
    Rcpp::traits::input_parameter< const int >::type dj_cutoff(dj_cutoffSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coxph_logL_gradient_efron_dist(beta, ind_machine_, useLocal, dj_cutoff, time, event, z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_aggregate
arma::mat rcpp_aggregate(const arma::mat& x, const arma::vec& indices, const bool simplify, const bool cumulative, const bool reversely);
RcppExport SEXP _pda_rcpp_aggregate(SEXP xSEXP, SEXP indicesSEXP, SEXP simplifySEXP, SEXP cumulativeSEXP, SEXP reverselySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< const bool >::type simplify(simplifySEXP);
    Rcpp::traits::input_parameter< const bool >::type cumulative(cumulativeSEXP);
    Rcpp::traits::input_parameter< const bool >::type reversely(reverselySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_aggregate(x, indices, simplify, cumulative, reversely));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cc_log_plk
double rcpp_cc_log_plk(NumericVector beta, List covariate_list, List failure_position, IntegerVector failure_num, List risk_sets, List risk_set_weights, int site_num);
RcppExport SEXP _pda_rcpp_cc_log_plk(SEXP betaSEXP, SEXP covariate_listSEXP, SEXP failure_positionSEXP, SEXP failure_numSEXP, SEXP risk_setsSEXP, SEXP risk_set_weightsSEXP, SEXP site_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type covariate_list(covariate_listSEXP);
    Rcpp::traits::input_parameter< List >::type failure_position(failure_positionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type failure_num(failure_numSEXP);
    Rcpp::traits::input_parameter< List >::type risk_sets(risk_setsSEXP);
    Rcpp::traits::input_parameter< List >::type risk_set_weights(risk_set_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type site_num(site_numSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cc_log_plk(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cc_pool_fun
double rcpp_cc_pool_fun(NumericVector beta, List covariate_list, List failure_position, IntegerVector failure_num, List risk_sets, List risk_set_weights, int K);
RcppExport SEXP _pda_rcpp_cc_pool_fun(SEXP betaSEXP, SEXP covariate_listSEXP, SEXP failure_positionSEXP, SEXP failure_numSEXP, SEXP risk_setsSEXP, SEXP risk_set_weightsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type covariate_list(covariate_listSEXP);
    Rcpp::traits::input_parameter< List >::type failure_position(failure_positionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type failure_num(failure_numSEXP);
    Rcpp::traits::input_parameter< List >::type risk_sets(risk_setsSEXP);
    Rcpp::traits::input_parameter< List >::type risk_set_weights(risk_set_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cc_pool_fun(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, K));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cc_grad_plk
NumericVector rcpp_cc_grad_plk(NumericVector beta, List covariate_list, List failure_position, IntegerVector failure_num, List risk_sets, List risk_set_weights, int site_num);
RcppExport SEXP _pda_rcpp_cc_grad_plk(SEXP betaSEXP, SEXP covariate_listSEXP, SEXP failure_positionSEXP, SEXP failure_numSEXP, SEXP risk_setsSEXP, SEXP risk_set_weightsSEXP, SEXP site_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type covariate_list(covariate_listSEXP);
    Rcpp::traits::input_parameter< List >::type failure_position(failure_positionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type failure_num(failure_numSEXP);
    Rcpp::traits::input_parameter< List >::type risk_sets(risk_setsSEXP);
    Rcpp::traits::input_parameter< List >::type risk_set_weights(risk_set_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type site_num(site_numSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cc_grad_plk(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cc_hess_plk
NumericMatrix rcpp_cc_hess_plk(NumericVector beta, List covariate_list, List failure_position, IntegerVector failure_num, List risk_sets, List risk_set_weights, int site_num);
RcppExport SEXP _pda_rcpp_cc_hess_plk(SEXP betaSEXP, SEXP covariate_listSEXP, SEXP failure_positionSEXP, SEXP failure_numSEXP, SEXP risk_setsSEXP, SEXP risk_set_weightsSEXP, SEXP site_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type covariate_list(covariate_listSEXP);
    Rcpp::traits::input_parameter< List >::type failure_position(failure_positionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type failure_num(failure_numSEXP);
    Rcpp::traits::input_parameter< List >::type risk_sets(risk_setsSEXP);
    Rcpp::traits::input_parameter< List >::type risk_set_weights(risk_set_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type site_num(site_numSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cc_hess_plk(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pda_coordi_cho", (DL_FUNC) &_pda_coordi_cho, 5},
    {"_pda_coordi_c", (DL_FUNC) &_pda_coordi_c, 5},
    {"_pda_cum_sum", (DL_FUNC) &_pda_cum_sum, 2},
    {"_pda_cum_sum_cols", (DL_FUNC) &_pda_cum_sum_cols, 2},
    {"_pda_Xotimes2", (DL_FUNC) &_pda_Xotimes2, 1},
    {"_pda_rcpp_coxph_logL", (DL_FUNC) &_pda_rcpp_coxph_logL, 4},
    {"_pda_rcpp_coxph_logL_gradient", (DL_FUNC) &_pda_rcpp_coxph_logL_gradient, 4},
    {"_pda_rcpp_coxph_logL_hessian", (DL_FUNC) &_pda_rcpp_coxph_logL_hessian, 4},
    {"_pda_rcpp_coxph_logL_efron", (DL_FUNC) &_pda_rcpp_coxph_logL_efron, 4},
    {"_pda_rcpp_coxph_logL_gradient_efron", (DL_FUNC) &_pda_rcpp_coxph_logL_gradient_efron, 4},
    {"_pda_rcpp_coxph_logL_gradient_efron_dist", (DL_FUNC) &_pda_rcpp_coxph_logL_gradient_efron_dist, 7},
    {"_pda_rcpp_aggregate", (DL_FUNC) &_pda_rcpp_aggregate, 5},
    {"_pda_rcpp_cc_log_plk", (DL_FUNC) &_pda_rcpp_cc_log_plk, 7},
    {"_pda_rcpp_cc_pool_fun", (DL_FUNC) &_pda_rcpp_cc_pool_fun, 7},
    {"_pda_rcpp_cc_grad_plk", (DL_FUNC) &_pda_rcpp_cc_grad_plk, 7},
    {"_pda_rcpp_cc_hess_plk", (DL_FUNC) &_pda_rcpp_cc_hess_plk, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_pda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
