# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coordi_cho <- function(atilde, B, betainit, lambda, iter_max) {
    .Call('_pda_coordi_cho', PACKAGE = 'pda', atilde, B, betainit, lambda, iter_max)
}

coordi_c <- function(atilde, B, betainit, lambda, iter_max) {
    .Call('_pda_coordi_c', PACKAGE = 'pda', atilde, B, betainit, lambda, iter_max)
}

cum_sum <- function(x, reversely = FALSE) {
    .Call('_pda_cum_sum', PACKAGE = 'pda', x, reversely)
}

cum_sum_cols <- function(x, reversely = FALSE) {
    .Call('_pda_cum_sum_cols', PACKAGE = 'pda', x, reversely)
}

Xotimes2 <- function(X) {
    .Call('_pda_Xotimes2', PACKAGE = 'pda', X)
}

rcpp_coxph_logL <- function(beta, time, event, z) {
    .Call('_pda_rcpp_coxph_logL', PACKAGE = 'pda', beta, time, event, z)
}

rcpp_coxph_logL_gradient <- function(beta, time, event, z) {
    .Call('_pda_rcpp_coxph_logL_gradient', PACKAGE = 'pda', beta, time, event, z)
}

rcpp_coxph_logL_hessian <- function(beta, time, event, z) {
    .Call('_pda_rcpp_coxph_logL_hessian', PACKAGE = 'pda', beta, time, event, z)
}

rcpp_coxph_logL_efron <- function(beta, time, event, z) {
    .Call('_pda_rcpp_coxph_logL_efron', PACKAGE = 'pda', beta, time, event, z)
}

rcpp_coxph_logL_gradient_efron <- function(beta, time, event, z) {
    .Call('_pda_rcpp_coxph_logL_gradient_efron', PACKAGE = 'pda', beta, time, event, z)
}

rcpp_coxph_logL_gradient_efron_dist <- function(beta, ind_machine_, useLocal, dj_cutoff, time, event, z) {
    .Call('_pda_rcpp_coxph_logL_gradient_efron_dist', PACKAGE = 'pda', beta, ind_machine_, useLocal, dj_cutoff, time, event, z)
}

rcpp_aggregate <- function(x, indices, simplify = TRUE, cumulative = FALSE, reversely = FALSE) {
    .Call('_pda_rcpp_aggregate', PACKAGE = 'pda', x, indices, simplify, cumulative, reversely)
}

rcpp_cc_log_plk <- function(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num) {
    .Call('_pda_rcpp_cc_log_plk', PACKAGE = 'pda', beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num)
}

rcpp_cc_pool_fun <- function(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, K) {
    .Call('_pda_rcpp_cc_pool_fun', PACKAGE = 'pda', beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, K)
}

rcpp_cc_grad_plk <- function(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num) {
    .Call('_pda_rcpp_cc_grad_plk', PACKAGE = 'pda', beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num)
}

rcpp_cc_hess_plk <- function(beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num) {
    .Call('_pda_rcpp_cc_hess_plk', PACKAGE = 'pda', beta, covariate_list, failure_position, failure_num, risk_sets, risk_set_weights, site_num)
}

